# Generated by Django 3.2.9 on 2021-11-09 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 11, 53, 37, 492442)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 11, 53, 37, 492442))),
        ),
    ]
