# Generated by Django 3.2.9 on 2021-11-09 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211109_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 9, 12, 7, 41, 259033), max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.CharField(default=models.CharField(default=datetime.datetime(2021, 11, 9, 12, 7, 41, 259033), max_length=10), max_length=10),
        ),
    ]
