# Generated by Django 3.2.9 on 2021-11-10 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20211109_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 10, 9, 54, 38, 219608), max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 10, 9, 54, 38, 219608), max_length=50),
        ),
    ]
