# Generated by Django 3.2.9 on 2021-11-10 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20211110_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 10, 11, 28, 5, 443094), max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 10, 11, 28, 5, 443094), max_length=50),
        ),
    ]
