# Generated by Django 3.2.9 on 2021-11-11 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20211110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 11, 13, 39, 45, 519666), max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 11, 13, 39, 45, 519666), max_length=50),
        ),
    ]
